package Game;


/**
* Game/ICell.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* 20 но€бр€ 2015 г. 22:37:06 MSK
*/

public interface ICell extends ICellOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICell
