package Game;


/**
* Game/ICellPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* 20 но€бр€ 2015 г. 22:37:06 MSK
*/

public abstract class ICellPOA extends org.omg.PortableServer.Servant
 implements Game.ICellOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getCell", new java.lang.Integer (0));
    _methods.put ("getID", new java.lang.Integer (1));
    _methods.put ("setCell", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Game/ICell/getCell
       {
         int $result = (int)0;
         $result = this.getCell ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Game/ICell/getID
       {
         String $result = null;
         $result = this.getID ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // Game/ICell/setCell
       {
         int value = in.read_long ();
         String ID = in.read_string ();
         this.setCell (value, ID);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Game/ICell:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ICell _this() 
  {
    return ICellHelper.narrow(
    super._this_object());
  }

  public ICell _this(org.omg.CORBA.ORB orb) 
  {
    return ICellHelper.narrow(
    super._this_object(orb));
  }


} // class ICellPOA
