package Game;

/**
* Game/ICellHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* 20 но€бр€ 2015 г. 22:37:06 MSK
*/

public final class ICellHolder implements org.omg.CORBA.portable.Streamable
{
  public Game.ICell value = null;

  public ICellHolder ()
  {
  }

  public ICellHolder (Game.ICell initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Game.ICellHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Game.ICellHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Game.ICellHelper.type ();
  }

}
