package Game;


/**
* Game/IGameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* 20 но€бр€ 2015 г. 22:37:06 MSK
*/

public interface IGameOperations 
{
  Game.ICell[] getGrid ();
  int gameIsReady ();
  String[] getID ();
  void connect (String ID);
  void disconnect (String ID);
} // interface IGameOperations
