package Game;

/**
* Game/IGameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* 20 но€бр€ 2015 г. 22:37:06 MSK
*/

public final class IGameHolder implements org.omg.CORBA.portable.Streamable
{
  public Game.IGame value = null;

  public IGameHolder ()
  {
  }

  public IGameHolder (Game.IGame initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Game.IGameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Game.IGameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Game.IGameHelper.type ();
  }

}
