package Game.IGamePackage;


/**
* Game/IGamePackage/gridHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* 20 ������ 2015 �. 22:37:06 MSK
*/

public final class gridHolder implements org.omg.CORBA.portable.Streamable
{
  public Game.ICell value[] = null;

  public gridHolder ()
  {
  }

  public gridHolder (Game.ICell[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Game.IGamePackage.gridHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        Game.IGamePackage.gridHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Game.IGamePackage.gridHelper.type ();
  }

}
