package Game;


/**
* Game/ICellOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* 20 но€бр€ 2015 г. 22:37:06 MSK
*/

public interface ICellOperations 
{
  int getCell ();
  String getID ();
  void setCell (int value, String ID);
} // interface ICellOperations
