package Game;


/**
* Game/IGamePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* 20 но€бр€ 2015 г. 22:37:06 MSK
*/

public abstract class IGamePOA extends org.omg.PortableServer.Servant
 implements Game.IGameOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getGrid", new java.lang.Integer (0));
    _methods.put ("gameIsReady", new java.lang.Integer (1));
    _methods.put ("getID", new java.lang.Integer (2));
    _methods.put ("connect", new java.lang.Integer (3));
    _methods.put ("disconnect", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Game/IGame/getGrid
       {
         Game.ICell $result[] = null;
         $result = this.getGrid ();
         out = $rh.createReply();
         Game.IGamePackage.gridHelper.write (out, $result);
         break;
       }

       case 1:  // Game/IGame/gameIsReady
       {
         int $result = (int)0;
         $result = this.gameIsReady ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // Game/IGame/getID
       {
         String $result[] = null;
         $result = this.getID ();
         out = $rh.createReply();
         Game.IGamePackage.str2Helper.write (out, $result);
         break;
       }

       case 3:  // Game/IGame/connect
       {
         String ID = in.read_string ();
         this.connect (ID);
         out = $rh.createReply();
         break;
       }

       case 4:  // Game/IGame/disconnect
       {
         String ID = in.read_string ();
         this.disconnect (ID);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Game/IGame:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IGame _this() 
  {
    return IGameHelper.narrow(
    super._this_object());
  }

  public IGame _this(org.omg.CORBA.ORB orb) 
  {
    return IGameHelper.narrow(
    super._this_object(orb));
  }


} // class IGamePOA
