package Game.IGamePackage;


/**
* Game/IGamePackage/gridHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* 20 но€бр€ 2015 г. 22:37:06 MSK
*/

abstract public class gridHelper
{
  private static String  _id = "IDL:Game/IGame/grid:1.0";

  public static void insert (org.omg.CORBA.Any a, Game.ICell[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Game.ICell[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Game.ICellHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (100, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Game.IGamePackage.gridHelper.id (), "grid", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Game.ICell[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Game.ICell value[] = null;
    int _len0 = istream.read_long ();
    if (_len0 > (100))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value = new Game.ICell[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Game.ICellHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Game.ICell[] value)
  {
    if (value.length > (100))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Game.ICellHelper.write (ostream, value[_i0]);
  }

}
